name: flutter_module
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

# annotation:
  openapi_generator_annotations: ^4.11.0
  json_annotation: ^4.8.1


#  state management:
  riverpod_annotation: ^2.1.2
  flutter_riverpod: ^2.3.7


#  utility:
  random_x: ^0.3.1
  logger: ^2.0.1
  intl: ^0.17.0
  equatable: ^2.0.5
  collection: ^1.17.1

#  data layer:
  petstore_api:
    path: ./api/petstore

  hello:
    path: ./api/hello

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  openapi_generator: ^4.12.1
  riverpod_generator: ^2.2.6
  json_serializable: ^6.7.1


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule
