name: flutter_module
description: A new Flutter module project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #  environment:
  flutter_dotenv: ^5.1.0

  #  localization:
  intl: any

  # annotation:
  openapi_generator_annotations: ^4.13.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.1.2

  #  state management:
  flutter_riverpod: ^2.3.7

  #  geo location:
  geolocator: ^10.0.0
  geocoding: ^2.1.0

  #  utility:
  logger: ^1.0.0
  equatable: ^2.0.5
  collection: ^1.17.1

  #  data layer:
  petstore_api:
    path: ./api/petstore

  hello:
    path: ./api/hello

  weather_api:
    path: ./api/weather_api

  #  fake data:
  random_x: ^0.3.1

  # navigation router:
  go_router: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  openapi_generator: ^4.13.1
  riverpod_generator: ^2.2.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule

  generate: true
flutter_intl:
  enabled: true

