name: flutter_module
description: A new Flutter module project.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

#  lib versions:
isar_version: &isar_version 3.1.0+1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #  localization:
  intl: any

  # annotation:
  openapi_generator_annotations: ^4.13.1
  json_annotation: ^4.8.1

  #  state management:
  flutter_riverpod: ^2.3.7
  riverpod_annotation: ^2.1.2

  #  geo location:
  geolocator: ^10.0.0
  geocoding: ^2.1.0

  #  utility:
  logger: ^1.0.0
  equatable: ^2.0.5
  collection: ^1.17.1
  path_provider: ^2.1.1

  #  fake data:
  random_x: ^0.3.1

  # navigation router:
  go_router: ^12.1.3

  #  database:
  isar: *isar_version
  isar_flutter_libs: *isar_version

  #  data layer:
  petstore_api:
    path: ./api/petstore
  hello:
    path: ./api/hello
  weather_api:
    path: ./api/weather_api

# 開發階段使用的套件，不會被打包進 app 中
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.4
  openapi_generator: ^4.13.1
  riverpod_generator: ^2.2.6
  json_serializable: ^6.7.1
  isar_generator: *isar_version

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.flutter_module
    iosBundleIdentifier: com.example.flutterModule

  generate: true
flutter_intl:
  enabled: true

